apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  DB_HOST: mysql-hostname
  DB_USER: mysql-username
  DB_PASSWORD: mysql-password
  DB_DATABASE: mysql-database
  server-port: "5000"
  check-interval: "30s"
  created-addresses: "/path/to/created-addresses.txt"
  database-server: "127.0.0.1"