version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5000
    ports:
      - '5000:5000'
    restart: "no"
    networks:
      - mynetwork
    volumes:
      - myvolume:/path/to/volume


networks:
  mynetwork:

volumes:
  myvolume: