apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: mortezasf/ftest1:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: configmap
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: server-port
        - name: CHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: check-interval
        - name: CREATED_ADDRESSES
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: created-addresses
        - name: DATABASE_SERVER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database-server
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"